Clone of Old Apple Page
babs257/apple-page pull request #1
Opened 2019-09-15 20:08 UTC by babs257

2019-09-16 19:00 UTC, wathigo commented
## Hello @babs257 
**Good work so far**, 
just a couple of things required to mark this as complete.

1. Add the config files for linting in your project. See [this](https://github.com/microverseinc/linters-config#linters-config) for more info. You have integrated the repository with stickler-ci and added an empty `.stickler.yml` but you need add the required configurations in the file to make this work. You should correct all offenses pointed out by the linter check.

2. Add a meaningful name for the Pull Request. Remember to include a description of the tasks you have completed in the Pull Request.

3. The background image you have used contains both the bottom four elements and 
the navigation bar. Include the four bottom elements with background images. 
They should be links. Hint: _use flex to style them_.

4. Make sure the background image used does not contain a navigation bar. Am not sure
if the styles for the navigation bar are coming from your styles or the background image. 

5. Make use of semantic html5 elements. Make sure you page contains 
[semantic HTML](https://www.w3schools.com/html/html5_semantic_elements.asp). Include `header` element containing the nav and `main` element containing the main part of the page. 

6. Make sure you don't use the original screenshot to bypass the requirements.

Please do necessary changes then submit another request for review.

Feel free to reach out via slack using or [twitter](https://twitter.com/simon_wathigo) if you need further clarifications.

_I have noticed that you have used a background image for the project.
Please use a background image only when necessary. The goal of this project
is to test you ability to style a page and should contain the page structure, i.e 
`header`, `main`, `footer`. Use a background image only for specific elements of the page
that have a background image._

2019-09-16 19:20 UTC, wathigo commented
## Hello @babs257 
**Good work so far**, 
just a couple of things required to mark this as complete.

1. Add the config files for linting in your project. See [this](https://github.com/microverseinc/linters-config#linters-config) for more info. You have integrated the repository with stickler-ci and added an empty `.stickler.yml` but you need add the required configurations in the file to make this work. You should correct all offenses pointed out by the linter check.

2. Add a meaningful name for the Pull Request. Remember to include a description of the tasks you have completed in the Pull Request.

3. The background image you have used contains both the bottom four elements and 
the navigation bar. Include the four bottom elements with background images. 
They should be links. Hint: _use flex to style them_.

4. Make sure the background image used does not contain a navigation bar. Am not sure
if the styles for the navigation bar are coming from your styles or the background image. 

5. Make use of semantic html5 elements. Make sure you page contains 
[semantic HTML](https://www.w3schools.com/html/html5_semantic_elements.asp). Include `header` element containing the nav and `main` element containing the main part of the page. 

6. Make sure you don't use the original screenshot to bypass the requirements.

Please do necessary changes then submit another request for review.

Feel free to reach out via slack using or [twitter](https://twitter.com/simon_wathigo) if you need further clarifications.

_I have noticed that you have used a background image for the project.
Please use a background image only when necessary. The goal of this project
is to test you ability to style a page and should contain the page structure, i.e 
`header`, `main`, `footer`. Use a background image only for specific elements of the page
that have a background image._

2019-09-16 19:41 UTC, wathigo requested changes
## Hello @babs257 
**Good work so far**, 
just a couple of things required to mark this as complete.

1. Add the config files for linting in your project. See [this](https://github.com/microverseinc/linters-config#linters-config) for more info. You have integrated the repository with stickler-ci and added an empty `.stickler.yml` but you need add the required configurations in the file to make this work. You should correct all offenses pointed out by the linter check.

2. Add a meaningful name for the Pull Request. Remember to include a description of the tasks you have completed in the Pull Request.

3. The background image you have used contains both the bottom four elements and 
the navigation bar. Include the four bottom elements with background images. 
They should be links. Hint: _use flex to style them_.

4. Make sure the background image used does not contain a navigation bar. Am not sure
if the styles for the navigation bar are coming from your styles or the background image. 

5. Make use of semantic html5 elements. Make sure you page contains 
[semantic HTML](https://www.w3schools.com/html/html5_semantic_elements.asp). Include `header` element containing the nav and `main` element containing the main part of the page. 

6. Make sure you don't use the original screenshot to bypass the requirements.

7. Remove inline CSS in your HTML code.

**Please do necessary changes then submit another request for review.**

Feel free to reach out via slack using or [twitter](https://twitter.com/simon_wathigo) if you need further clarifications.

_I have noticed that you have used a background image for the project.
Please use a background image only when necessary. The goal of this project
is to test you ability to style a page and should contain the page structure, i.e 
`header`, `main`, `footer`. Use a background image only for specific elements of the page
that have a background image._

2019-09-16 19:41 UTC, wathigo commented on index.html
> +				<form id="search-form" action="#" method="post"><i class="fa fa-search" style="width:  15px; height: 14px; margin-left: 6px; margin-top: 3px;"></i>
[REQUIRED] Remove inline styles Include all your styles in the external CSS file

2019-09-16 19:41 UTC, wathigo commented on styles/style.css
> +    background-image: url("https://archive.fo/UW4oR/bf13112842d2dd0160466e36cfafac05d80eeb41/scr.png");
[Required] Don't use a a background image to bypass requirements.

2019-09-20 07:02 UTC, samgaco requested changes
Hi @babs257 :high_brightness: 

Now is looking better :100: , I can see the effort you are putting in. Some more changes before we are able to give you the approval:

--------------

### Required:

1. Solve all the linter checks that have failed

> ![failed6](https://user-images.githubusercontent.com/34820784/65306088-e5dad280-db84-11e9-9e01-da522ea4b694.png)

2. The four boxes at the bottom should be aligned with float OR flex

### So, please just work on these 2 :crossed_fingers: points and submit back for another code review. Regards!
--------------

### Optional:

* Read more about  HTML semantic elements an implement a few more, like `<aside>` , `<section>` and `<article>` 
* Try to make the styling of the site looking closer to that of the original website. Right  now is looking a bit off and trying to make it look similar would force you to keep improving as a developer 

-----------------------

Moving forward have this into account :arrow_down: 

* **[For your next code review requests]**  Add a short summary of changes in Pull Request description


-------------

Summary: You have two required points 1. and 2. and two optional points right after.
* ###### STATUS OF THE PROJECT: REQUESTED CHANGES :stop_sign:

2019-09-20 07:02 UTC, samgaco commented on styles/style.css
> +  position: relative;
The section for **#footer-image** should be aligned using display flex or floats.

2019-09-21 19:37 UTC, bolah2009 requested changes
# Hi @babs257  :wave: 

### Nice job so far, good job with the navbar gradients too. :smile: 

#### Let's make [the clone](https://raw.githack.com/babs257/apple-page/dc1d962a1718cf50d150c6e042509817388a7a40/index.html) look like the [source page](https://web.archive.org/web/20140301004610/http://www.apple.com/) please.

The main objective of the project is using CSS Backgrounds effectively, the main background image should cover the whole page, remove the border from the page and add hover effects to the navbar accordingly. :relaxed: 

| Current | Preferred |
|:----:|:-----:|
|![image](https://user-images.githubusercontent.com/36057474/65378318-7e20a680-dcae-11e9-8386-b3246ebfea14.png) | ![image](https://user-images.githubusercontent.com/36057474/63733852-eb891500-c871-11e9-9989-2de9092b3fc5.png)|

Other things to note:
- Fix [HTML Validation errors/warnings](https://validator.w3.org/nu/?doc=https%3A%2F%2Fraw.githack.com%2Fbabs257%2Fapple-page%2Fdc1d962a1718cf50d150c6e042509817388a7a40%2Findex.html)
  > Validate your HTML markup with https://validator.w3.org/#validate_by_upload.
- Make `README` file more descriptive
  > Remember about descriptive README file.
- Let's make this Pull Request look more professional. [See below](https://github.com/babs257/apple-page/pull/1#pullrequestreview-291477910)
  - [**NEXT PROJECT**]: Use meaningful commits messages. [Learn more here](https://www.freecodecamp.org/news/level-you-up-to-awesome-commit-messages-a85558cb90e8/)
  - [:heavy_check_mark: **Done**] Use meaningful names for Pull Requests.
  - [**REQUIRED**] Add a short summary of changes in Pull Request description.
- [NEXT PROJECTS]: For next (HTML/CSS) project, please follow `GitHub flow` [guidelines](https://microverse.pathwright.com/library/microverse-onboarding/86777/path/step/53987922/). What is missing here is a descriptive branch name instead of `feature-branch`, think of feature branch as a branch name that is descriptive enough to have an idea of what the branch is used for.

#### :recycle:  Make these changes and submit another code review request. :+1: 

#### Feel free to reach me on slack if you having issues implementing these features. :+1: 

Good luck with your next submission. :star2: 

Cheers
[Bola](https://bolabuari.com/)

###### PS: Note that comments tagged as `OPTIONAL` are not part of the minimum requirements to approve this PR

2019-09-21 19:37 UTC, bolah2009 commented on README.md
> +In this project you’ll clone the website of one of the most design-forward companies in the world. It’s not a very complex site but it uses background photos well and the navbar at the top contains a
Let's make the `README` file more descriptive, details like what was done in the projects, what was learned, link to the assignment, clone and source page, screenshots of the clone page can make README look more professional.
 > Remember about descriptive README file.

2019-09-21 19:39 UTC, bolah2009 reviewed
# Update PR description

  ![update-PR-description-html](https://user-images.githubusercontent.com/36057474/64305800-6e078800-cf88-11e9-82f0-04e13fd6cb8d.gif)

2019-09-24 02:15 UTC, Redvanisation requested changes
### Hello @babs257  

**Good work so far 👍 but you still need to fix the following issues before I can give you a thumb's up ⬇️** 

1. Align the 4 bottom elements to the center just like the original page.

2. Fix markup validation errors on [here](https://validator.w3.org/).

### _After making the required changes please submit a new code review request_

### Good luck! 🍀

2019-09-24 10:49 UTC, stratospherique approved these changes
### Great work :clap: . You made all the necessary changes :100: . The project is approved :heavy_check_mark: and you can merge to master :+1: :+1:

2019-09-24 20:42 UTC, merged